version: '3'

networks:
  default:
    external:
      name: urls0

services:
  server:
    build: docker_image
    image: unshortenurl_server:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src/app
    command: ["python", "server.py"]
  worker:
    build: docker_image
    image: unshortenurl_worker:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./src:/usr/src/app
    command: ["python", "worker.py"]
    deploy:
      mode: replicated
      replicas: 64
  consumer:
    build: docker_image
    image: unshortenurl_consumer:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./src:/usr/src/app
      - ./:/data
    command: ["python", "consumer.py"]
  redis:
    image: redis:alpine
    volumes:
      - ./redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
  client:
    build: docker_image
    image: unshortenurl_client:latest
    depends_on:
      - server
    volumes:
      - ./src:/usr/src/app
      - ./:/data
    command: ["python", "client.py"]
  timeout_handler:
    build: docker_image
    image: unshortenurl_client:latest
    depends_on:
      - server
    volumes:
      - ./src:/usr/src/app
    command: ["python", "timeout_handler.py"]
  rqdashboard:
    image: docker.rech.priv.ina:5001/bmazoyer/rqdashboard
    ports:
      - 9181:9181
    depends_on:
      - redis
    command: rq-dashboard -H redis